## 파이썬 리뷰

## 파일 읽기 

In [13]:
# -*- coding: utf-8 -*-

fd=open("studentlist.txt")

FileNotFoundError: [Errno 2] No such file or directory: 'studentlist.txt'

In [37]:
fd.readline() # 헤딩 

lines= fd.readlines()

print ("line# : ", len(lines))

line# :  17


## 필드 분할, type 가공

In [49]:
Table=[] # 전체 레코드를 담은 테이블 

for line in lines :  # 한 줄 씩  line 변수에 담아서
    
    fields= line.split(",") # , 를 기준으로 나눈다. -> fields라는 list가 만들어진다.
    # name,sex,age,grade,absence,bloodtype,height,weight,dept
    #  0    1   2    3    4        5         6     7      8

    fields[2]= int(fields[2])  # 나이를 숫자로 바꿔 넣기

    fields[6]= float(fields[6])  # 키를 숫자로 바꿔 넣기
    fields[7] = float(fields[7]) # 몸무게도 
    fields[8]= fields[8].strip()
          
    Table.append(fields)  #레코드를 테이블에 추가

print (Table[1:3])

[['이미린', '여자', 22, '2', '무', 'AB', 170.1, 53.0, '03'], ['홍길동', '남자', 24, '4', '무', 'B', 175.0, 80.1, '01']]


## 정렬

In [39]:
Table= sorted(Table, key = lambda col : col[2] ) # 나이로 정렬
for record in Table :
    print ( record[0], record[1], record[2])

손세수 여자 20
박미희 여자 21
김민수 남자 21
여수근 남자 21
이미린 여자 22
강수친 여자 22
방희철 남자 22
임동민 남자 22
김미진 여자 22
김길동 남자 23
김철수 남자 23
이희수 여자 23
이철린 남자 23
이희진 여자 23
홍길동 남자 24
박수호 남자 24
김동수 남자 24


## 기술 통계 : 평균 구하기, 키 평균

In [40]:
heightSum=0
for rec in Table :
    height= rec[6]
    heightSum+=height

print (heightSum / len(Table))

170.03529411764706


## 기술통계 :  도수 구하기 

### 학과 별 학생 수 

In [41]:
dept_dic= {}  # {학과 코드: 도수}
for rec in Table :
    dept_code=rec[8]
    if dept_code in dept_dic:
        dept_dic[dept_code]+=1
    else :
        dept_dic[dept_code]=1

print (dept_dic)

{'01': 6, '03': 6, '02': 5}


## Join 
### 학과 코드 파일 읽어서 도수 결과에 표기

In [42]:
deptcode={}  # {학과 코드 : 실제 명칭}

f=open("deptcode.txt") 
for line in f:
    code, name=line.split(",")
    deptcode[code]=name.strip()
    print (deptcode)

for key, value in deptcode.items():
    print (key, value)

for key, value in dept_dic.items():
    print (deptcode[key], value) 

{'01': '소프트웨어'}
{'01': '소프트웨어', '02': 'AI융합'}
{'01': '소프트웨어', '02': 'AI융합', '03': '통계보험'}
01 소프트웨어
02 AI융합
03 통계보험
소프트웨어 6
통계보험 6
AI융합 5


## group by :  혈액형 별 키 평균

### 혈액형 별 키 합계, 도수 집계  

In [43]:
b_table={}  # 집계 테이블 : { 혈액형 : [합계, 도수] }

for rec in Table :
    bloodtype=rec[5]
    if bloodtype in b_table:  # 진료과목이 있는지
        b_table[bloodtype]= [ b_table[bloodtype][0]+rec[6], b_table[bloodtype][1]+ 1]  # 키 합계, 갯수 
    else:
        b_table[bloodtype]= [rec[6], 1]  # 키 , 갯수 

print ( b_table)

{'A': [676.3, 4], 'O': [825.7, 5], 'AB': [532.2, 3], 'B': [856.4, 5]}


In [44]:
for key, value in b_table.items():
    print ( key , value[0]/value[1] )

A 169.075
O 165.14000000000001
AB 177.4
B 171.28


## *과제 1 : 성별, 혈액형 별 몸무게의 평균

결과예시)

남자, A, 얼마

남자, B, 얼마

### 제출방법 

본 파일 제출 (기존 내용 그대로 포함)

In [66]:
w_table={}  # 집계 테이블 : { 혈액형 : [합계, 도수] }

for rec in Table :
    gender = rec[1]
    bloodtype=rec[5]
    weight = rec[7]
    
    if (gender, bloodtype) in w_table:  # 진료과목이 있는지
        w_table[gender, bloodtype]= [ w_table[(gender,bloodtype)][0]+weight, w_table[(gender,bloodtype)][1]+ 1]  # 키 합계, 갯수 
    else:
        w_table[gender, bloodtype]= [weight, 1]  # 키 , 갯수 
    
for key, value in w_table.items() :
    print ( key[0], key[1], value[0]/value[1] )

남자 O 65.1
여자 AB 53.0
남자 B 68.95
남자 AB 80.75
여자 A 52.25
여자 O 50.13333333333333
남자 A 58.75
여자 B 45.2


---

# Numpy

## 기본
ndarray : 1가지 type의 값들로 구성, axis = 차원

### 속성

- ndarray.ndim : 차원수
- ndarray.shape : 데이터 모양
- ndarray.size : 전체 값 개수
- ndarray.dtype : 값의 type
- ndarray.itemsize : 각 값의 크기 (byte)


In [15]:
import numpy as np

ar1= np.arange(15).reshape (3,5)

ar1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
ar1.shape

(3, 5)

In [17]:
ar1.ndim

2

In [18]:
ar1.size

15

### 생성

- np.array ( 파이썬 리스트 ) 
- np.zeros (shape )  or np.ones , np.empty
- np.arrange (size) or np.arange (시작, 끝, 간격) 

In [19]:
np.array ( [1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [20]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.arange(5, 20, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

## Operations

### 기본
- 사칙연산 : 벡터* 스칼라  => 각 element와 스칼라 연산
- 각 element 에 적용되는 연산:  exp(), sqrt() .. 
- 벡터 * 벡터 => 일반 벡터연산이 아니고, 같은 위치의 element 끼리 연산
- 벡터 곱은 @
- += 도 동작함 

In [23]:
A = np.array( [[1,2], [3,4]])
B = np.array ( [[2,3], [4,5]])

A

array([[1, 2],
       [3, 4]])

In [24]:
A*4

array([[ 4,  8],
       [12, 16]])

In [25]:
A+=3
A

array([[4, 5],
       [6, 7]])

In [26]:
A+B

array([[ 6,  8],
       [10, 12]])

In [27]:
np.sqrt(A)

array([[2.        , 2.23606798],
       [2.44948974, 2.64575131]])

In [28]:
A*B

array([[ 8, 15],
       [24, 35]])

In [29]:
A@B   # 내적 연산

array([[28, 37],
       [40, 53]])

### random 
- randn(모양) :  정규분포
- randint (최소값, 최대값, size=) : 정수 

In [30]:
np.random.randn(3,2)

array([[-0.95563044,  1.15797481],
       [ 0.06663621, -0.57480841],
       [ 1.06581454, -1.5306431 ]])

In [31]:
np.random.randint(1, 100, size=6).reshape(3,2)

array([[64, 10],
       [70, 62],
       [ 9, 90]])

### sum, max, min
- 기본 : 전체 array에서 


In [32]:
A.sum()

22

In [33]:
A.min()

4

### (중요) axis에 따른 연산

- 주요 파라메터 : axis =차원 기준 
- sum (axis=0 ) : 첫번째 차원으로 합
- sum (axis=1 ) : 두번째 차원으로 합

In [34]:
B=np.arange(12).reshape (3,4)  # 첫번째 차원 =3개 element , 두번째 차원 =각기 element 는 4개 짜리 array
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
B.sum (axis=0) # 3개의 element 끼리 더함

array([12, 15, 18, 21])

In [36]:
B.sum (axis=1) # 2번째 차원의 4개의 element 끼리 평균

array([ 6, 22, 38])

In [37]:
B.max( axis=0)

array([ 8,  9, 10, 11])

## Indexing, slicing


- 1차원 : element A[2],  범위 A[2:5]
    - A[ (1,2,4)] :  multi index
- 2차원 : element B[2,3] , 범위 B [1:3, : ] ,   : 는 전체를 의미

In [38]:
A=np.arange (5, 15, 1)
print (A)
print (A[2])


[ 5  6  7  8  9 10 11 12 13 14]
7


In [39]:
print (A[(2,4),]) # 첫번째 axis에 대한 것을 명시 필요

[7 9]


In [40]:
A[1:3]

array([6, 7])

In [ ]:
B=np.arange(30).reshape((5,6))
B

In [ ]:
B[3,2]

In [ ]:
B[3, 2:4]

In [ ]:
C=np.arange(45).reshape((5,3,3))
C

In [ ]:
C[:,:,1:2]

- ...  : 중간 idx 생략  

In [ ]:
C[..., 1]    

In [ ]:
C[1, ...]

In [ ]:
C[1,...,1]

## 과제 2 : np.arange(30).reshape((5,6)) 에서 0,2,4.. column (axis=1) 만 뽑아서 새로운 array를 만드시오


In [2]:
import numpy as np

def calculate_entropy_based_fitness(path, coordinates):
    distances = []
    for i in range(len(path) - 1):
        distances.append(euclidean_distance(coordinates[path[i]], coordinates[path[i+1]]))
    distances.append(euclidean_distance(coordinates[path[-1]], coordinates[path[0]]))
    
    distance_distribution = np.array(distances) / sum(distances)
    entropy = -np.sum(distance_distribution * np.log(distance_distribution))
    
    total_distance = sum(distances)
    return entropy / total_distance